kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim
  namespace: test-pvc
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: test-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
