apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
  labels:
    app: nfs-client-provisioner
  # replace with namespace where provisioner is deployed
  namespace: test-pvc
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: k8s-sigs.io/nfs-subdir-external-provisioner
            - name: NFS_SERVER
              value: sfcsweb.mic.com.tw # must same as volumes.nfs.server
            - name: NFS_PATH
              value: /data/nfs-share # must same as volumes.nfs.path
      volumes:
        - name: nfs-client-root
          nfs:
            server: sfcsweb.mic.com.tw # NFS server hostname or ip address
            path: /data/nfs-share # nfs share path, recommend backup periodically
