kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim
  namespace: test-pvc
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
